events { worker_connections 1024; }

http {
    upstream backend  { server backend:8000; }
    upstream ml       { server ml-engine:8001; }
    upstream mlintern { server ml-intern:8002; }
    upstream frontend { server frontend:80; }

    server {
        listen 80;
        server_name _;

        location /api/ml/ {
            proxy_pass         http://ml/api/ml/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_read_timeout 120s;
        }

        location /api/ml-intern/ {
            proxy_pass         http://mlintern/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_read_timeout 180s;
        }

        location /api/ {
            proxy_pass         http://backend/api/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            client_max_body_size 100M;
            proxy_read_timeout 120s;
        }

        location / {
            proxy_pass http://frontend/;
            proxy_set_header Host $host;
        }
    }
}
